format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1901-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.cice.r.1901-01-01-00000.nc
  hashes:
    binhash: 80b3ee2b18354a4dab9cec97132f7467
    md5: 2f74ad164cbefe7164ba0a1c7c28997c
work/access-om3.cpl.r.1901-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.cpl.r.1901-01-01-00000.nc
  hashes:
    binhash: 49272c568e8e08e60f7804c5ce29afc9
    md5: 7dde051816f73df7589e257639983a39
work/access-om3.datm.r.1901-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.datm.r.1901-01-01-00000.nc
  hashes:
    binhash: 94d4de1c836a4ff2195662dc35db7233
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1901-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.drof.r.1901-01-01-00000.nc
  hashes:
    binhash: c70d891e324070f8eafedf7105f4e892
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1901-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.mom6.r.1901-01-01-00000.nc
  hashes:
    binhash: d737ae1096662438eff8123028cf9d4f
    md5: e86603f2b1a251914282d086773c0151
work/access-om3.mom6.r.1901-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.mom6.r.1901-01-01-00000_1.nc
  hashes:
    binhash: 4b0c4142683da58d557d5d0815b5cad9
    md5: e6c8aad4c722eead9c76292873495126
work/access-om3.mom6.r.1901-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.mom6.r.1901-01-01-00000_2.nc
  hashes:
    binhash: 91f6d3fd76605cecf09e0c775abddff0
    md5: 836f086014d2425c70243e5d7785ef81
work/access-om3.mom6.r.1901-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/access-om3.mom6.r.1901-01-01-00000_3.nc
  hashes:
    binhash: 61bb3fb9794a7ccf44fa522b3cbc68cb
    md5: 4230383e76b17610a4464b53ce74e885
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/rpointer.atm
  hashes:
    binhash: 2fd5a36ccd41a6cbf6460e22ee588b7a
    md5: 27b9497bb722e90e6800014f4c37f772
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/rpointer.cpl
  hashes:
    binhash: 82d9f3c3ac622d7a12336d3cba50a4c8
    md5: 2bc9d4f79a64e7898accd6647c4d677c
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/rpointer.ice
  hashes:
    binhash: bd671532402c5a4be3fd6171e05ed18d
    md5: e9c3c58fc10dd4114d2079fec8d2bfc8
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/rpointer.ocn
  hashes:
    binhash: 73b7fed8bd82a8c2d8470c18762bab8c
    md5: 898205e7216238aacaaee10172f0117e
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart000/rpointer.rof
  hashes:
    binhash: 1fe23eabc23f7d08839964e804625c9f
    md5: 52f906041c01a134d4e1349bc653ca44
