format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1946-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.cice.r.1946-01-01-00000.nc
  hashes:
    binhash: 7fef0511fe6ae40e575814618b5bb991
    md5: 900bb7ad85aa4aad68db05ef8dea9790
work/access-om3.cpl.r.1946-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.cpl.r.1946-01-01-00000.nc
  hashes:
    binhash: c2a7bf06dab2ea9898ffd0c575418293
    md5: e8c1937544d6a5ef04fe2ae18c60c37a
work/access-om3.datm.r.1946-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.datm.r.1946-01-01-00000.nc
  hashes:
    binhash: 3c32f0bc6b33e839200d99981ff65ea8
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1946-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.drof.r.1946-01-01-00000.nc
  hashes:
    binhash: 98004902039909722b7ac3243f1b8f6c
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1946-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.mom6.r.1946-01-01-00000.nc
  hashes:
    binhash: 5f3be90955d50fd45029d9a8ab18b27c
    md5: ad76c4f8b26ad94b0553a649e047f8cc
work/access-om3.mom6.r.1946-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.mom6.r.1946-01-01-00000_1.nc
  hashes:
    binhash: 304415a0bfd5e302acb5c5472bb5ddf2
    md5: 7631719dab30270288193e0ed99a3f3d
work/access-om3.mom6.r.1946-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.mom6.r.1946-01-01-00000_2.nc
  hashes:
    binhash: 8daad8d286ac748a56fdc361a6e7a7ce
    md5: bfd157fff4eb472c71938336032913d2
work/access-om3.mom6.r.1946-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/access-om3.mom6.r.1946-01-01-00000_3.nc
  hashes:
    binhash: e3685fbc1172d15ef81d502ed65bfe34
    md5: 00e36b55e20b838c3b732be4d3a7b2ba
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/rpointer.atm
  hashes:
    binhash: 28de378191d3bb1271cf111060fb0c91
    md5: 407738057edde2502056202887bcf522
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/rpointer.cpl
  hashes:
    binhash: f2d0238c63eb0cdb4c877cf28352ab8d
    md5: a02fd03ede47397ae4f559bacf3103eb
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/rpointer.ice
  hashes:
    binhash: 489e704461360088ec30bef831f1820d
    md5: 4d1b38bb940cd34d8fa5c2de07feb1b2
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/rpointer.ocn
  hashes:
    binhash: c216781fd46aeefb476af7ff48108daa
    md5: fe889462914fad234388bbfc977d233b
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart015/rpointer.rof
  hashes:
    binhash: 391a3aa79d4390a53dc26766644f9165
    md5: 4bb4ba08d67b562461d72d320db870bc
