format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1922-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.cice.r.1922-01-01-00000.nc
  hashes:
    binhash: 1e9d9ec4265cd52eea305cbe8126bf9b
    md5: 4d0471869b1b3c7f7720fb9d9c02b8c5
work/access-om3.cpl.r.1922-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.cpl.r.1922-01-01-00000.nc
  hashes:
    binhash: d1ca59ceab1c53d1de7e24e428c0161e
    md5: 7f713a9ae511f1dbc3315c8a03a26618
work/access-om3.datm.r.1922-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.datm.r.1922-01-01-00000.nc
  hashes:
    binhash: 1dd4c77d5c8d1bc7b77f432521c49e2b
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1922-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.drof.r.1922-01-01-00000.nc
  hashes:
    binhash: bda3dc05412a7fcdb432d503ff88c645
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1922-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.mom6.r.1922-01-01-00000.nc
  hashes:
    binhash: a5ad1826567549c4cff9355663344367
    md5: 95fb26f09046b613097582ddd835436c
work/access-om3.mom6.r.1922-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.mom6.r.1922-01-01-00000_1.nc
  hashes:
    binhash: a49e0788e4e9d6200ed7686fd2441360
    md5: 36ecbee0a4e3928e52807c7603ec1df6
work/access-om3.mom6.r.1922-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.mom6.r.1922-01-01-00000_2.nc
  hashes:
    binhash: a61521b770d0f084a29f3a8a80218665
    md5: caaebbc5e938f7e30ef1db86e5cc5195
work/access-om3.mom6.r.1922-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/access-om3.mom6.r.1922-01-01-00000_3.nc
  hashes:
    binhash: f76c7945b93bc6a37d5e03d71cb3af7e
    md5: fd318d34580392a7d4d7773fb03af68a
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/rpointer.atm
  hashes:
    binhash: 706b44ae78e6c1782bed80ca70f50e98
    md5: a56f965822ae05e392e84a0a1bda3051
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/rpointer.cpl
  hashes:
    binhash: edd8c2faf8ef4b55c0842f9150e95ac5
    md5: c77d02b53f07e3a9f832b87936c80eeb
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/rpointer.ice
  hashes:
    binhash: 2f3dc2ea3fa5c7f84fb80470e6c8719f
    md5: ab3fc70f7c0488719b15ca518f56a430
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/rpointer.ocn
  hashes:
    binhash: 25b86a245d5c4e77a37b8b5d1c5a52f0
    md5: 9544aad2c29a79263709dd98f2c9c952
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart007/rpointer.rof
  hashes:
    binhash: 1cd12dc263f3d1e43122e00ecb9d8b3c
    md5: 3d4b79104b2034c072ba6d0b60455494
