format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1931-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.cice.r.1931-01-01-00000.nc
  hashes:
    binhash: d401eb661463dba5747b825f1f14f2e6
    md5: 28124d0caa8bf6561946a2b8e242bd06
work/access-om3.cpl.r.1931-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.cpl.r.1931-01-01-00000.nc
  hashes:
    binhash: 660d68ab9de5c31385c25b21472299ea
    md5: d4b4c6fc88460572c3ed4a43f2779763
work/access-om3.datm.r.1931-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.datm.r.1931-01-01-00000.nc
  hashes:
    binhash: 3a1209878b5656e9d4b90dc535a81727
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1931-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.drof.r.1931-01-01-00000.nc
  hashes:
    binhash: bffa3f6c2501b702d20dc0975b75fe9e
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1931-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.mom6.r.1931-01-01-00000.nc
  hashes:
    binhash: 95bc7a9a2bcf1be5a985081ba6fc46a0
    md5: aee526cc7a20408a3327403956a9780c
work/access-om3.mom6.r.1931-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.mom6.r.1931-01-01-00000_1.nc
  hashes:
    binhash: 162bf710430510d05f66698e39daf237
    md5: 3a26ccde1a522851c7e89337c070519a
work/access-om3.mom6.r.1931-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.mom6.r.1931-01-01-00000_2.nc
  hashes:
    binhash: c4f8a358129686f365870cf1ec58a61a
    md5: fd7b0482b53be96096a1cfbf5d778185
work/access-om3.mom6.r.1931-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/access-om3.mom6.r.1931-01-01-00000_3.nc
  hashes:
    binhash: 75f5a25ceb813af39b4643c0efa8e374
    md5: afcdc76c7c8037ae5b4c38c3acd5d44c
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/rpointer.atm
  hashes:
    binhash: d212ce8f147de359ad9ab002b26b0212
    md5: 3fd3d80641e84f60e6faa8490022dacf
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/rpointer.cpl
  hashes:
    binhash: adfb56d937ef46ccfbfb096d4ff12238
    md5: 9741d16e642c5b206dfea7f754fcc0e1
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/rpointer.ice
  hashes:
    binhash: 8ee490566393ae44354a203e83aefab5
    md5: 6334a7021c6345364ac0d56eb2d3af49
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/rpointer.ocn
  hashes:
    binhash: 646633984a172644c91c1c36ffeec558
    md5: 2736302a4f0c5dba2628d0c1a509730c
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart010/rpointer.rof
  hashes:
    binhash: 99922ea8a318b8ff419c019208e243c6
    md5: 655df6fb44200e4871a02cb6b952d8fb
