format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1907-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.cice.r.1907-01-01-00000.nc
  hashes:
    binhash: f7eb6113c646ce7c8c0429bbd98510a5
    md5: 36875263e8dc50e721aaed26753b51f2
work/access-om3.cpl.r.1907-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.cpl.r.1907-01-01-00000.nc
  hashes:
    binhash: 8331999289e1df2098af6bc9359e45ce
    md5: 37180a02ee0cb648db16496488b01f06
work/access-om3.datm.r.1907-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.datm.r.1907-01-01-00000.nc
  hashes:
    binhash: 4a074a938df871f07b9737ece662bbb1
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1907-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.drof.r.1907-01-01-00000.nc
  hashes:
    binhash: f0585a3a7e1fd9c6525922278d782f38
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1907-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.mom6.r.1907-01-01-00000.nc
  hashes:
    binhash: 8ca683020d92e82b25bc17413f8e1bbd
    md5: f53df4c50b3bfabf361a8b2163ae8755
work/access-om3.mom6.r.1907-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.mom6.r.1907-01-01-00000_1.nc
  hashes:
    binhash: 294dea229e757b4c7da13246e29bed1f
    md5: 1ca6542370f2c2dee3413a1b6c05f64d
work/access-om3.mom6.r.1907-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.mom6.r.1907-01-01-00000_2.nc
  hashes:
    binhash: b70c672e1684bcdea92656f59105a3f4
    md5: 24a088b7092e3b734f8d974c2b2deb68
work/access-om3.mom6.r.1907-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/access-om3.mom6.r.1907-01-01-00000_3.nc
  hashes:
    binhash: 021af14a6f407f17af74a8efdd93be27
    md5: 3bc34b1981ed52eff47d527a0a84a4ae
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/rpointer.atm
  hashes:
    binhash: 6542bd2b2549d176f0902920ea6b4f73
    md5: 7042d414707159811415c0d368bc456b
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/rpointer.cpl
  hashes:
    binhash: a01efd3166f96613f294ca4dc3440431
    md5: f5c494da8c4cb993154c085e5652b315
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/rpointer.ice
  hashes:
    binhash: 05d51eddc0d5df686e72b0a4c0a061b7
    md5: 921b98772a9f0c25b14151e386ce332e
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/rpointer.ocn
  hashes:
    binhash: 95ee38d8a215aab279ae801f8b82fec6
    md5: 4ebbd6bb7d6840228dea1f48d7ba53c8
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart002/rpointer.rof
  hashes:
    binhash: d168435b3f125f359afac982c7e40cdd
    md5: 6a27e65ff12986f6215f20f37a457c4f
