format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1928-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.cice.r.1928-01-01-00000.nc
  hashes:
    binhash: 0d970b2c4eb7c29331b2e915d6f3afc6
    md5: fac4426118c1c84209a7c4a829e57000
work/access-om3.cpl.r.1928-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.cpl.r.1928-01-01-00000.nc
  hashes:
    binhash: 31c89dfdae49c3c7efe1683e1c482328
    md5: e01830670f356239bef26dbaf2f10ea3
work/access-om3.datm.r.1928-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.datm.r.1928-01-01-00000.nc
  hashes:
    binhash: ef99af8aae80bf90685f40012f410337
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1928-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.drof.r.1928-01-01-00000.nc
  hashes:
    binhash: 5f040b0965cdcd1e5dbc63e1b9d71aa6
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1928-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.mom6.r.1928-01-01-00000.nc
  hashes:
    binhash: c716bc4a1e733e372a04ae63c1f882b5
    md5: 2093a5b032ce6b720ef4034caeec0f60
work/access-om3.mom6.r.1928-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.mom6.r.1928-01-01-00000_1.nc
  hashes:
    binhash: ed71e988a821e2cf8b64cd8c39afda9d
    md5: ea1ebfce89b0fc652b0834fe91bb81c8
work/access-om3.mom6.r.1928-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.mom6.r.1928-01-01-00000_2.nc
  hashes:
    binhash: 67b50de20ee0993cc39ef1c00a376b84
    md5: cb50ae69151c02d2eef10b54d9a7caf0
work/access-om3.mom6.r.1928-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/access-om3.mom6.r.1928-01-01-00000_3.nc
  hashes:
    binhash: 40dcafdaf2fa7f93b7b70d19a13f6d6d
    md5: 33fc6e881b17bab14967c42c609f2a44
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/rpointer.atm
  hashes:
    binhash: e4fa6fa1bc3dfd9d3a0a512067f760f8
    md5: 43aea9158635f626ed6a8819669748e1
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/rpointer.cpl
  hashes:
    binhash: 24afd70a130606d2206ee444ef79d445
    md5: b38e3ab9f1d65fca5eb2f5526317dccd
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/rpointer.ice
  hashes:
    binhash: b884cb45b1234f13e0ac2dfbf41c5e95
    md5: 08a5379758d379d25732ceab3bf00e2b
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/rpointer.ocn
  hashes:
    binhash: a3c4b2a74ad0187b711f0d06f450bbc2
    md5: 8f676a5c986664eafab36966197141ea
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart009/rpointer.rof
  hashes:
    binhash: d22ba2e2fe08f74c1faf1fa39c10f35f
    md5: 0f271c367bc60274fe6cba59c69a179e
