format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1949-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.cice.r.1949-01-01-00000.nc
  hashes:
    binhash: 487447ba79bf641565434b07be51cf1b
    md5: ba0d6cfb21ff9f7702202091d16ed702
work/access-om3.cpl.r.1949-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.cpl.r.1949-01-01-00000.nc
  hashes:
    binhash: 94e0bcf860ca6c05b6670da2818025ce
    md5: 0930e7a21f4d2c6fd441e70ab944cd9f
work/access-om3.datm.r.1949-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.datm.r.1949-01-01-00000.nc
  hashes:
    binhash: f3f96c358e9920a6452a3487b3691342
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1949-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.drof.r.1949-01-01-00000.nc
  hashes:
    binhash: 3509ec4d208e4d8f46a6a3328fefacf1
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1949-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.mom6.r.1949-01-01-00000.nc
  hashes:
    binhash: 1ca5d470f211968d9d3f84fadf503f36
    md5: 36f9b4522e787a6b131f7b93432be36d
work/access-om3.mom6.r.1949-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.mom6.r.1949-01-01-00000_1.nc
  hashes:
    binhash: 4c68ed3ca6227f3772f8d483d44a83e2
    md5: 5b4662d84a94020c8bf58431f126efd9
work/access-om3.mom6.r.1949-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.mom6.r.1949-01-01-00000_2.nc
  hashes:
    binhash: 8a4c24f3f72428a3e2c2355678e096f7
    md5: 4c36bb64bfa48485bb02bad55f6b0623
work/access-om3.mom6.r.1949-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/access-om3.mom6.r.1949-01-01-00000_3.nc
  hashes:
    binhash: 13e9e4322ce64f7d12420e9baaa78c43
    md5: eeb9965f6c920dfea5c103b0f9389b50
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/rpointer.atm
  hashes:
    binhash: 5814b6ace8c0e9e407fe24879f5a6998
    md5: dabf83637967054b6e940ecbe76bd5aa
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/rpointer.cpl
  hashes:
    binhash: ea0324aa3fc46b90bf47a36cf3cb7bb2
    md5: f18a45709667930a23eba8a2837189cf
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/rpointer.ice
  hashes:
    binhash: bde87f6c441ad2245f5bb97a1b3e8aee
    md5: 62f764566c97d14822307d07ec25e3fb
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/rpointer.ocn
  hashes:
    binhash: 788b368c3dd25dec4667555a200f22d9
    md5: ed71fb00f0c1dd713586f8cec7b0a135
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart016/rpointer.rof
  hashes:
    binhash: 63a6917e89bbb035f2dbf697d33d9e43
    md5: aa90fc1f9b203dc9e82e61852890669b
