format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1925-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.cice.r.1925-01-01-00000.nc
  hashes:
    binhash: f2abf3edb55825bfb7ec83d55d7d2c6a
    md5: 39580b15ccfee41a5f32e326a88fe641
work/access-om3.cpl.r.1925-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.cpl.r.1925-01-01-00000.nc
  hashes:
    binhash: edbcd49b6d3344b79098ba7983e7b156
    md5: 5f54ffca4e79cb9c7479a2913e876bd3
work/access-om3.datm.r.1925-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.datm.r.1925-01-01-00000.nc
  hashes:
    binhash: 7ac65bbe0f35a44dda7166e45e025fa3
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1925-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.drof.r.1925-01-01-00000.nc
  hashes:
    binhash: ae704fb9ace91d80f0bb8bb20a45b381
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1925-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.mom6.r.1925-01-01-00000.nc
  hashes:
    binhash: 0ffaa33d0c3ddd327f5eacd424f91902
    md5: da391651f773ab62b1e89969bb99ac78
work/access-om3.mom6.r.1925-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.mom6.r.1925-01-01-00000_1.nc
  hashes:
    binhash: 005773152936f3b69457d3555c440ae6
    md5: 4f0bc4dab67283a41ce5d507d0b4a040
work/access-om3.mom6.r.1925-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.mom6.r.1925-01-01-00000_2.nc
  hashes:
    binhash: 33579ec2779f91e7a07f0594704d26a3
    md5: 9cc9eac0b88c35f3049b906ee6cbc534
work/access-om3.mom6.r.1925-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/access-om3.mom6.r.1925-01-01-00000_3.nc
  hashes:
    binhash: 2e97573ddeb3f85c06e803b8db37fda1
    md5: 439dc190a90523565f6d2b1a5ae0de70
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/rpointer.atm
  hashes:
    binhash: 18550b5fbfd3a13821da9150dd6a3b9f
    md5: d70aa406f2cac3ac8f7b4c46b6523d3e
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/rpointer.cpl
  hashes:
    binhash: 1c97cf223bea2e957b8b7b7605ca7799
    md5: e06897579e67254b7ebfc36a36acc03f
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/rpointer.ice
  hashes:
    binhash: 3f1c2336230a9e6b73556159ebd31927
    md5: 9e8ae8a7b10009e9401e897bab7aaa48
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/rpointer.ocn
  hashes:
    binhash: 06f543106c169bc9d181b76c2c3cfb19
    md5: cb163633b0748b99790c66bd07b8f1f3
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart008/rpointer.rof
  hashes:
    binhash: 016a3e9dd199898fa6c406c0ea461d72
    md5: 6f1e7a57fa655c8d4e731e8ab8bca2d0
