format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1943-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.cice.r.1943-01-01-00000.nc
  hashes:
    binhash: 8ac9f606dbc6525bb702e7205501f090
    md5: 80459e35514b8b1da0b0c9aa737b691e
work/access-om3.cpl.r.1943-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.cpl.r.1943-01-01-00000.nc
  hashes:
    binhash: 00835a9ce1477a8d5fbb6f355c9e51fa
    md5: cd14cac5f982949932d33544247e0f89
work/access-om3.datm.r.1943-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.datm.r.1943-01-01-00000.nc
  hashes:
    binhash: d21f0dd8cce1ae0acd5c09786d944bd2
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1943-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.drof.r.1943-01-01-00000.nc
  hashes:
    binhash: 90492e58391f186093c74e502cb28b60
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1943-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.mom6.r.1943-01-01-00000.nc
  hashes:
    binhash: e2ea4b81532f70ef7a8e07b26c0842cd
    md5: 139fedc0b65afb8a86388a15476ae68f
work/access-om3.mom6.r.1943-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.mom6.r.1943-01-01-00000_1.nc
  hashes:
    binhash: 46a3acafdc8e18b6821aba695c5d2a69
    md5: 3a11aee6c37c22d79235257897c3f495
work/access-om3.mom6.r.1943-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.mom6.r.1943-01-01-00000_2.nc
  hashes:
    binhash: 848efe733906f29f94086991f8aa857e
    md5: 449c1249abe34ec8580cd126cf922f22
work/access-om3.mom6.r.1943-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/access-om3.mom6.r.1943-01-01-00000_3.nc
  hashes:
    binhash: 0a78af453457f3899a49d69bf5c4085c
    md5: c0a972134a1a2044a341a990f4254edf
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/rpointer.atm
  hashes:
    binhash: a7069c2dffcf2d5bb8fdb28de981122b
    md5: b31e54a63c2f384307ffc74835fc1086
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/rpointer.cpl
  hashes:
    binhash: ecf1d5d3d6379e59a3c9c42851cecc1a
    md5: 4741df7ceb2ae30300a741d0f3566699
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/rpointer.ice
  hashes:
    binhash: 78c7e66d02e9bbf571f6e96a6680bdf6
    md5: 80121e4c5c982c82765b3c300967661f
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/rpointer.ocn
  hashes:
    binhash: b54bfb0fc5c3c020e5655dd8b68be8ce
    md5: 18284f60a473c516853fa68cc7eaf8c2
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart014/rpointer.rof
  hashes:
    binhash: d3bee2ceafb4d14b4c4937710cb3cc41
    md5: 15780aa934de58a17073548a32c501ec
