format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1916-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.cice.r.1916-01-01-00000.nc
  hashes:
    binhash: cf4a4de635f951ed0731fb496aed9d79
    md5: 4ae7baa6ed8b5edba1ce13db5e773766
work/access-om3.cpl.r.1916-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.cpl.r.1916-01-01-00000.nc
  hashes:
    binhash: 6fc7d6455239fdbe7d615a61e2dd972a
    md5: cfd26a7a4372db8c07ccdebd101854e6
work/access-om3.datm.r.1916-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.datm.r.1916-01-01-00000.nc
  hashes:
    binhash: dcbcf9ca7e541c6d8e59a736a6aabb49
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1916-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.drof.r.1916-01-01-00000.nc
  hashes:
    binhash: 81d78ee4c26c9ba424cdd5b1f021c4a3
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1916-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.mom6.r.1916-01-01-00000.nc
  hashes:
    binhash: f00a124d945349ec67091d57335b907a
    md5: 4463972d99eb215b0814cb2a781e7e9a
work/access-om3.mom6.r.1916-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.mom6.r.1916-01-01-00000_1.nc
  hashes:
    binhash: b709e8c93d9e27cfe7c53099553ae633
    md5: d820bf0c328073b269ebcf7e890d09f4
work/access-om3.mom6.r.1916-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.mom6.r.1916-01-01-00000_2.nc
  hashes:
    binhash: 736039300d4e370f0da6f06b110a2518
    md5: 9e98781098b35c43f474313415365a74
work/access-om3.mom6.r.1916-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/access-om3.mom6.r.1916-01-01-00000_3.nc
  hashes:
    binhash: 4377d488397d487871e894c1f3efdf70
    md5: a158ddce8097550757b1dc9379c2eaee
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/rpointer.atm
  hashes:
    binhash: 55a0ee45bb39319a1cee9f7481b9d4ad
    md5: 50a10edaa154bf2a9ee752276b8ad0fd
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/rpointer.cpl
  hashes:
    binhash: 3bbd912290b9523cbb3d58da167d33b5
    md5: cd9f84f8b4c70a505c4ad9d102c37f61
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/rpointer.ice
  hashes:
    binhash: 8876cf685a77e8a6ee4e1c09c4b8388b
    md5: 0785db97a284be677af13474f96f4055
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/rpointer.ocn
  hashes:
    binhash: f46e8f5d0ce24e339bb60072f9107706
    md5: d3b6119c86a9dae98b5416e709195f4a
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart005/rpointer.rof
  hashes:
    binhash: 7e43c1ea832744cd23d18a91399632fe
    md5: 84975abd562b49a50a498d16b875c78d
