format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1902-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.cice.r.1902-01-01-00000.nc
  hashes:
    binhash: 90d16a3edfdd7f4464872d6a8991f00e
    md5: ecfaf84d5e9f86f88e2def0adbe63f2c
work/access-om3.cpl.r.1902-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.cpl.r.1902-01-01-00000.nc
  hashes:
    binhash: 6b6698228df8b19c7205114c9f42db2a
    md5: 9f1ac98ca63df81401369d53ebac6797
work/access-om3.datm.r.1902-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.datm.r.1902-01-01-00000.nc
  hashes:
    binhash: 6365a99b6fbd4011f986b44948b3fb84
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1902-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.drof.r.1902-01-01-00000.nc
  hashes:
    binhash: fae85f3793230615744d687c0eb32579
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1902-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.mom6.r.1902-01-01-00000.nc
  hashes:
    binhash: 795674ad0936a1d23a587babbb0527a5
    md5: 05209853fa37d01bb61dde8086b53337
work/access-om3.mom6.r.1902-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.mom6.r.1902-01-01-00000_1.nc
  hashes:
    binhash: ffde236211fa71f2a191449ef7188da6
    md5: 7f02e0392df3d4b91c14931746152640
work/access-om3.mom6.r.1902-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.mom6.r.1902-01-01-00000_2.nc
  hashes:
    binhash: eae0d74fea533a68d0f2a4cbab8575db
    md5: 04938c8c6d0391545be117a393ff81e3
work/access-om3.mom6.r.1902-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/access-om3.mom6.r.1902-01-01-00000_3.nc
  hashes:
    binhash: b06c8b344ba5108ae8cb19349a5b50f3
    md5: d011a2e075c395599e3b0ef68a3c5052
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/rpointer.atm
  hashes:
    binhash: ccc2de90e4134977b1e67660dbbfd6ff
    md5: bcb92aec1d77f39f9204e1754a5e3114
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/rpointer.cpl
  hashes:
    binhash: 5d6a88d4c7604b29294638fcd80aa69d
    md5: 6948b9c48e36f90602f9cdcd1e08196a
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/rpointer.ice
  hashes:
    binhash: 64febddaf3125f2f6293d20e05a25e1d
    md5: 9713ca474f93aabcde263b9339c71fab
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/rpointer.ocn
  hashes:
    binhash: 2412c7dad3f1529015179bea60cead0b
    md5: 071f34a268a429848c46b07ac57a4842
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart001/rpointer.rof
  hashes:
    binhash: 4eb7336946e1a48722e99b4477d20cd7
    md5: f480de8eb0d6f8f209fb12006478055c
