format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1910-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.cice.r.1910-01-01-00000.nc
  hashes:
    binhash: d1ea91e605ba91039f28bc98cca56980
    md5: 2954cd64700e9a816e2749722f2e7daf
work/access-om3.cpl.r.1910-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.cpl.r.1910-01-01-00000.nc
  hashes:
    binhash: c15684e516106dd12aa466695f8e41e7
    md5: b0a8dde7b95bc12e78efa0497d1f2895
work/access-om3.datm.r.1910-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.datm.r.1910-01-01-00000.nc
  hashes:
    binhash: 1d4c0053545d662ec5e460c5cc419718
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1910-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.drof.r.1910-01-01-00000.nc
  hashes:
    binhash: b1538510dc8095dbdb71e89b241e39bb
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1910-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.mom6.r.1910-01-01-00000.nc
  hashes:
    binhash: 90d74cbdb259cea7833189b344211f72
    md5: 7d40b4adb40c9e7e8bbd91d1acf99033
work/access-om3.mom6.r.1910-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.mom6.r.1910-01-01-00000_1.nc
  hashes:
    binhash: 182ed3c168fe5c6f65443b0e4a3f5631
    md5: c614cc0e7c1daf1083122fa97f2e292a
work/access-om3.mom6.r.1910-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.mom6.r.1910-01-01-00000_2.nc
  hashes:
    binhash: f720ab0925e46c1cf764c7704d3ec172
    md5: e28582ecaea7482f32cb82f7ba6df6ef
work/access-om3.mom6.r.1910-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/access-om3.mom6.r.1910-01-01-00000_3.nc
  hashes:
    binhash: 564c726b6d21de6652e004ca951fe7fe
    md5: cb7dc6424204afa31f273564c5b0b7cd
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/rpointer.atm
  hashes:
    binhash: f9a7d081b7c42a31595af986b7ca1427
    md5: c447e9501fa6dfe42e90ed976640620f
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/rpointer.cpl
  hashes:
    binhash: 9b625aae711229b10eb42af20d3ee61e
    md5: f39cbc9860bc9cedcca34256ae86686d
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/rpointer.ice
  hashes:
    binhash: b9cb0bb572fe31ee00c9aad757b0e4eb
    md5: 7fbe8560d16d38128f554733ce5a8f42
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/rpointer.ocn
  hashes:
    binhash: e2c18946f5498fad6f8136d48728dbc0
    md5: d8542a3db3665526cfab5456fc0a4858
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart003/rpointer.rof
  hashes:
    binhash: 556d23fcf5449f7bf896364a7372f189
    md5: d643415551f9d60f9adb0ff50d46768f
