format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1913-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.cice.r.1913-01-01-00000.nc
  hashes:
    binhash: a5b3c88e7e97f57f1a89d5cc9e04e5b1
    md5: 0dc16b2c702e4471b285b260257f1677
work/access-om3.cpl.r.1913-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.cpl.r.1913-01-01-00000.nc
  hashes:
    binhash: aa9237400c6ea7f8655752c2f077389f
    md5: 6c454c694e7582351dad6e3d43ddff11
work/access-om3.datm.r.1913-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.datm.r.1913-01-01-00000.nc
  hashes:
    binhash: aa77c40f6488626b4c727af49eb7253a
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1913-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.drof.r.1913-01-01-00000.nc
  hashes:
    binhash: ceb1fef254b87eff7d1fcd1d174a2d34
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1913-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.mom6.r.1913-01-01-00000.nc
  hashes:
    binhash: 1bf9f7d70a2bd4b56f734842cce48e65
    md5: c71cd2a1f9747ad244a28a582d904f67
work/access-om3.mom6.r.1913-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.mom6.r.1913-01-01-00000_1.nc
  hashes:
    binhash: 95e9ee6fa7abb9fec1b16b92046b7aac
    md5: b683ace9870cda3b8947aa8c5779839e
work/access-om3.mom6.r.1913-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.mom6.r.1913-01-01-00000_2.nc
  hashes:
    binhash: e2af3627cf14fca483b0e6d6a91a2e9b
    md5: f178d42eaa8443bee2dd2f036c67324e
work/access-om3.mom6.r.1913-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/access-om3.mom6.r.1913-01-01-00000_3.nc
  hashes:
    binhash: 442ce01fa6a440b691cb730cce02b296
    md5: 16c61018e0c9ff89f8d3fb652389b588
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/rpointer.atm
  hashes:
    binhash: dddf780ebd00d4e39faeb12d9da7ccee
    md5: 642b56019e50fcf5e91f5a3b032e9485
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/rpointer.cpl
  hashes:
    binhash: 6559ee82ab72ad4f3f3d3f144e218938
    md5: 761a1f7e0db63273719e4b1fde17a486
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/rpointer.ice
  hashes:
    binhash: ca6d45b960615ec3729938a85c3fecfe
    md5: b6de1f319aa4035c6cd533530c514d79
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/rpointer.ocn
  hashes:
    binhash: 8874d468f4b31f3e4d13ad7648342325
    md5: 4fa12d9031121a99c178edfdc6d2c162
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart004/rpointer.rof
  hashes:
    binhash: be0f6451af854136f56821a0f892e45e
    md5: 68ebf1626ac404d9a7c33c5195a472c5
