format: yamanifest
version: 1.0
---
work/access-om3.cice.r.1950-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.cice.r.1950-01-01-00000.nc
  hashes:
    binhash: e75623b78ebd181badd773d24f149da3
    md5: 44af06c84723b7edcf92cf86cf5a0859
work/access-om3.cpl.r.1950-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.cpl.r.1950-01-01-00000.nc
  hashes:
    binhash: 38dd32bdcd95c2d47dc6320318729dd2
    md5: 49699271442a3c2d8f6805448a79528f
work/access-om3.datm.r.1950-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.datm.r.1950-01-01-00000.nc
  hashes:
    binhash: 759d1bcdbe8f9f70e307e698e8e5c6a3
    md5: 5d611bdad83ee20c059a1d70b5e24b50
work/access-om3.drof.r.1950-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.drof.r.1950-01-01-00000.nc
  hashes:
    binhash: c7e6432154055d09516cecfab4074f4b
    md5: 03df84d2630fb48b4aa86a876d2ba417
work/access-om3.mom6.r.1950-01-01-00000.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.mom6.r.1950-01-01-00000.nc
  hashes:
    binhash: 5685d87a2a054b844342530a7f8305df
    md5: 79bec268e37070b4c96254b85d34bc3d
work/access-om3.mom6.r.1950-01-01-00000_1.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.mom6.r.1950-01-01-00000_1.nc
  hashes:
    binhash: 0cfce27d99e0233a7dcf38a432b6041f
    md5: 28ea6ad5f8e5e4175384b414592b9fdd
work/access-om3.mom6.r.1950-01-01-00000_2.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.mom6.r.1950-01-01-00000_2.nc
  hashes:
    binhash: 464ee8c06590ddaaa49516d169310231
    md5: bc0378007c9895b6842adb1dd6d39345
work/access-om3.mom6.r.1950-01-01-00000_3.nc:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/access-om3.mom6.r.1950-01-01-00000_3.nc
  hashes:
    binhash: 11d1938b83762497ee55a02ccd4ca9be
    md5: 5a42cbf7637a2568e196d4e22622d51e
work/rpointer.atm:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/rpointer.atm
  hashes:
    binhash: 802cdf0a9b3e02d8805e8d09c44227bb
    md5: c21e5d09eced5820f4dbae34002c3d1e
work/rpointer.cpl:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/rpointer.cpl
  hashes:
    binhash: 116986a0e1fb8dd46ddbd032ca38c90a
    md5: 9474d79251899fd1d39b33c7b2ef269b
work/rpointer.ice:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/rpointer.ice
  hashes:
    binhash: 8826bc0e852fd83c17b78696099d37ea
    md5: dc7d1dfb83c7e7b1be12b598dd176cb3
work/rpointer.ocn:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/rpointer.ocn
  hashes:
    binhash: 03da16c99e17699f2b2e959396982c36
    md5: d1a187f8d2713d0c73a2ecbf6cb8dbab
work/rpointer.rof:
  fullpath: /scratch/tm70/ml0072/access-om3/archive/test_current_config_0.0_w_rho_coord_with_GM_RR-RR_w_gm_w_rho-cdfb3543/restart017/rpointer.rof
  hashes:
    binhash: abe336e7b25b98a4380f33a8c1f6aca8
    md5: 380501aedd57d51fd3cb970d9fd2e6b5
